name: CD

on:
  push:
    branches: [ "main" ]

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Continuous Delivery
        uses: actions/upload-artifact@4
        with:
          name: compact.zip
          path: |
            README.md

  deploy:
    runs-on: ubuntu-latest
    needs: deliver
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: compact.zip
      - name: Display download files
        run: ls -R
